using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ShoppingCart.API.Models
{
    /// <summary>
    /// Data model that holds the result after a new user is created.
    /// This model intentionally does not contain password property for security reasons.
    /// </summary>
    public class UserResultModel
    {
        /// <summary>
        /// Autogenerated ID that uniquely identifies each user with their unique ID.
        /// </summary>
        /// <example>1</example>
        [SwaggerSchema(ReadOnly = true)]
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }
        /// <summary>
        /// Username of the user.
        /// </summary>
        /// <example>karthik</example>
        [Required] // Failure to provide Username in the request causes model validation to fail (400 -  "The Username field is required.")
        [JsonPropertyName("Username")]
        public string Username { get; set; }
        /// <summary>
        /// Email address of the user.
        /// </summary>
        /// <example>karthik@gmail.com</example>
        [Required]
        [JsonPropertyName("Email")]
        public string Email { get; set; }
        /// <summary>
        /// Phone numer of the user.
        /// </summary>
        /// <example>9940568874</example>
        [Required]
        [JsonPropertyName("Phone")]
        public long Phone { get; set; }
    }
}
