/**
 * Data model that holds information related to a cart item.
 */
export interface ICartitemModel {
  /// <summary>
  /// Autogenerated ID that uniquely identifies each cart item.
  /// </summary>
  /// <example>1</example>
  cartID: number;
  /// <summary>
  /// Uniquely identifies each cart item with a unique order id
  /// </summary>
  /// <example>1</example>
  orderID: number;
  /// <summary>
  /// Uniquely identifies each order with the user.
  /// </summary>
  /// <example>1</example>
  userID: number;
  /// <summary>
  /// Username of the user.
  /// </summary>
  /// <example>karthik</example>
  username: string;
  /// <summary>
  /// Represents a unique product added to the cart
  /// </summary>
  /// <example>1</example>
  productID: number;
  /// <summary>
  /// Product name of the cart item
  /// </summary>
  /// <example>Branded Foods</example>
  productname: string;
  /// <summary>
  /// Defines the price of this product
  /// </summary>
  /// <example>100</example>
  productPrice: number;
}
