/**
 * Defines the data model for a single product.
 */
export interface IProductModel {
  /// <summary>
  /// Uniquely identifies each product with it's unique ID.
  /// </summary>
  /// <example>1</example>
  productID: number;
  /// <summary>
  /// Uniquely identifies each product category with it's unique ID.
  /// </summary>
  /// <example>1</example>
  productCategoryID: number;
  /// <summary>
  /// Defines the category name of this product
  /// </summary>
  /// <example>Branded Foods</example> 
  productCategoryName: string;
  /// <summary>
  /// Defines the name of this product
  /// </summary>
  /// <example>Pepsi</example>
  productName: string;
  /// <summary>
  /// Defines the price of this product
  /// </summary>
  /// <example>100</example>
  productPrice: number;
  /// <summary>
  /// Defines the description of this product
  /// </summary>
  /// <example>A product from ABC company</example>
  productDescription: string;
  /// <summary>
  /// Defines the image name of this product which is autogenerated by the server
  /// </summary>
  productImageName: string;
  /// <summary>
  /// Defines the image API URL from the server
  /// </summary>
  /// <example>https://localhost:44398/images/1.png</example>
  productImageURL: string;
}
