using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ShoppingCart.API.Models
{
    /// <summary>
    /// Data model that holds information related to a product.
    /// </summary>
    public class ProductModel : IProductModel
    {
        /// <summary>
        /// Autogenerated ID that uniquely identifies each product with it's unique ID.
        /// </summary>
        /// <example>1</example>
        [SwaggerSchema(ReadOnly = true)]
        [Required]
        [JsonPropertyName("ProductID")]
        public int ProductID { get; set; }
        /// <summary>
        /// Uniquely identifies each product category with it's unique ID.
        /// </summary>
        /// <example>1</example>
        [SwaggerSchema(ReadOnly = true)]
        [Required]
        [JsonPropertyName("ProductCategoryID")]
        public int ProductCategoryID { get; set; }
        /// <summary>
        /// Defines the category this product belongs to
        /// </summary>
        /// <example>Branded Foods</example>
        [Required]
        [JsonPropertyName("ProductCategoryName")]
        public string ProductCategoryName { get; set; }
        /// <summary>
        /// Defines the name of this product
        /// </summary>
        /// <example>Pepsi</example>
        [Required]
        [JsonPropertyName("ProductName")]
        public string ProductName { get; set; }
        /// <summary>
        /// Defines the price of this product
        /// </summary>
        /// <example>100</example>
        [Required]
        [JsonPropertyName("ProductPrice")]
        public int ProductPrice { get; set; }
        /// <summary>
        /// Defines the description of this product
        /// </summary>
        /// <example>A product from ABC company</example>
        [Required]
        [JsonPropertyName("ProductDescription")]
        public string ProductDescription { get; set; }
        /// <summary>
        /// Defines the image in binary format to be saved in a server location
        /// </summary>
        /// <example>Binary object</example>
        [Required]
        [JsonPropertyName("ProductImage")]
        public IFormFile ProductImage { get; set; }
        /// <summary>
        /// Defines the image name of this product which is autogenerated by the server
        /// </summary>
        [JsonPropertyName("ProductImageName")]
        public string ProductImageName { get; set; }
        /// <summary>
        /// Defines the image API URL from the server
        /// </summary>
        /// <example>https://localhost:44398/images/1.png</example>
        [JsonPropertyName("ProductImageURL")]
        public string ProductImageURL { get; set; }
    }
}
