using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ShoppingCart.API.Models
{
    /// <summary>
    /// Data model that holds information related to a cart.
    /// </summary>
    public class CartItemModel : ICartItemModel
    {
        /// <summary>
        /// Autogenerated ID that uniquely identifies each cart item.
        /// </summary>
        /// <example>1</example>
        [SwaggerSchema(ReadOnly = true)]
        [JsonPropertyName("CartID")]
        public int CartID { get; set; }
        /// <summary>
        /// Uniquely identifies each cart item with a unique order id
        /// </summary>
        /// <example>1</example>
        [SwaggerSchema(ReadOnly = true)]
        [Required]
        [JsonPropertyName("OrderID")]
        public int OrderID { get; set; }
        /// <summary>
        /// Uniquely identifies each order with the user.
        /// </summary>
        /// <example>1</example>
        [JsonPropertyName("UserID")]
        public int UserID { get; set; }
        /// <summary>
        /// Username of the user.
        /// </summary>
        /// <example>karthik</example>
        [Required]
        [JsonPropertyName("Username")]
        public string Username { get; set; }
        /// <summary>
        /// Represents a unique product added to the cart
        /// </summary>
        /// <example>1</example>
        [Required]
        [JsonPropertyName("ProductID")]
        public int ProductID { get; set; }
        /// <summary>
        /// Product name of the cart item
        /// </summary>
        /// <example>Branded Foods</example>
        [Required]
        [JsonPropertyName("Productname")]
        public string Productname { get; set; }
        /// <summary>
        /// Defines the price of this product
        /// </summary>
        /// <example>100</example>
        [Required]
        [JsonPropertyName("ProductPrice")]
        public int ProductPrice { get; set; }
    }
}
