using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;

namespace ShoppingCart.API.Models
{
    /// <summary>
    /// Data model that holds information related to a cart.
    /// </summary>
    public class CartItemCollectionModel
    {
        /// <summary>
        /// Uniquely identifies each cart item with a unique order id
        /// </summary>
        /// <example>1</example>
        [SwaggerSchema(ReadOnly = true)]
        public int OrderID { get; set; }
        /// <summary>
        /// Represents a unique product added to the cart
        /// </summary>
        /// <example>1</example>
        [Required]
        public int ProductID { get; set; }
        /// <summary>
        /// Product name of the cart item
        /// </summary>
        /// <example>Branded Foods</example>
        [Required]
        public string Productname { get; set; }
        /// <summary>
        /// Total quantity ordered by the user
        /// </summary>
        /// <example>2</example>
        public int Quantity { get; set; }
        /// <summary>
        /// Defines the total price for this product for the ordered quantity.
        /// </summary>
        /// <example>300</example>
        [Required]
        public long TotalAmount { get; set; }
        /// <summary>
        /// Defines the image name of this product which is autogenerated by the server
        /// </summary>
        /// <example>1.png</example>
        public string ProductImageName { get; set; }
        /// <summary>
        /// Defines the image API URL from the server
        /// </summary>
        /// <example>https://localhost:44398/images/1.png</example>
        public string ProductImageURL { get; set; }

        /// <summary>
        /// Uniquely identifies each order with the user.
        /// </summary>
        /// <example>1</example>
        public int UserID { get; set; }
        /// <summary>
        /// Username of the user.
        /// </summary>
        /// <example>karthik</example>
        [Required]
        public string Username { get; set; }
    }
}
