using System;
using System.Collections.Generic;
using System.Text;

namespace ShoppingCart.API.Models
{
    public interface ICartModel
    {
        /// <summary>
        /// Autogenerated ID that uniquely identifies each cart item.
        /// </summary>
        /// <example>1</example>
        public int CartID { get; set; }
        /// <summary>
        /// Uniquely identifies each cart item with a unique order id
        /// </summary>
        /// <example>1</example>
        public int OrderID { get; set; }
        /// <summary>
        /// Uniquely identifies each order with the user.
        /// </summary>
        /// <example>1</example>
        public int UserID { get; set; }
        /// <summary>
        /// Username of the user.
        /// </summary>
        /// <example>karthik</example>
        public string Username { get; set; }
        /// <summary>
        /// Represents a unique product added to the cart
        /// </summary>
        /// <example>1</example>
        public int ProductID { get; set; }
        /// <summary>
        /// Product name of the cart item
        /// </summary>
        /// <example>Branded Foods</example>
        public string Productname { get; set; }
        /// <summary>
        /// Defines the price of this product
        /// </summary>
        /// <example>100</example>
        public int ProductPrice { get; set; }
    }
}
